-- Generated by PixelPanic Seeding Script on 2025-08-17 13:01:58
-- Populates the 'issues' table with unique repair types.
-- Run this script first.

INSERT INTO issues (name) VALUES
  ('Back Glass Broken'),
  ('Back Panel Broken'),
  ('Battery Issue'),
  ('Broken Screen Glass'),
  ('Camera Glass Broken'),
  ('Charging Issue'),
  ('Diagnosis'),
  ('Display Broken'),
  ('Display Broken (OLED)'),
  ('Face ID'),
  ('Fingerprint Sensor Issue'),
  ('Flex Cable Replacement'),
  ('Front Camera Repair'),
  ('Inner Display Broken'),
  ('Microphone Issue'),
  ('Network Problem'),
  ('Outer Display Broken'),
  ('Power & Volume Button issue'),
  ('Rear Camera Repair'),
  ('Receiver Issue'),
  ('Storage Upgrade'),
  ('Wifi Problem')
ON CONFLICT (name) DO NOTHING;
